<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SYNPSZD4426" name="main.ManualUserStories.US_181526" tests="11" failures="1" timestamp="30 May 2018 15:42:34 GMT" time="286.058" errors="0">
  <testcase name="TC_04" time="18.757" classname="main.ManualUserStories.US_181526"/>
  <testcase name="TC_11" time="31.705" classname="main.ManualUserStories.US_181526"/>
  <testcase name="TC_10" time="31.873" classname="main.ManualUserStories.US_181526"/>
  <testcase name="TC_12" time="26.474" classname="main.ManualUserStories.US_181526"/>
  <testcase name="TC_13" time="34.710" classname="main.ManualUserStories.US_181526"/>
  <testcase name="TC_03" time="18.715" classname="main.ManualUserStories.US_181526"/>
  <testcase name="tc_01" time="29.017" classname="main.ManualUserStories.US_181526">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at main.ManualUserStories.US_181526.tc_01(US_181526.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- tc_01 -->
  <testcase name="tc_02" time="20.039" classname="main.ManualUserStories.US_181526"/>
  <testcase name="TC_08" time="28.182" classname="main.ManualUserStories.US_181526"/>
  <testcase name="TC_05" time="19.528" classname="main.ManualUserStories.US_181526"/>
  <testcase name="TC_09" time="27.058" classname="main.ManualUserStories.US_181526"/>
</testsuite> <!-- main.ManualUserStories.US_181526 -->
